package com.finadv.assets.service;

import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.OptionalInt;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;

import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.RandomStringUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.pdfbox.cos.COSDocument;
import org.apache.pdfbox.io.RandomAccessFile;
import org.apache.pdfbox.io.RandomAccessRead;
import org.apache.pdfbox.pdfparser.PDFParser;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.util.UriComponentsBuilder;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.finadv.assets.dto.UserAssetsDto;
import com.finadv.assets.entities.AssetInstrument;
import com.finadv.assets.entities.AssetType;
import com.finadv.assets.entities.CAMS;
import com.finadv.assets.entities.Equity;
import com.finadv.assets.entities.FundDataList;
import com.finadv.assets.entities.FundDataResponse;
import com.finadv.assets.entities.FundInfo;
import com.finadv.assets.entities.HolderInfo;
import com.finadv.assets.entities.Institution;
import com.finadv.assets.entities.MutualFundAnalysis;
import com.finadv.assets.entities.MutualFundAnalysisResponse;
import com.finadv.assets.entities.MutualFundAnalysisResponseList;
import com.finadv.assets.entities.MutualFundAnalysisScheme;
import com.finadv.assets.entities.NSDLAssetAmount;
import com.finadv.assets.entities.NSDLEquity;
import com.finadv.assets.entities.NSDLMutualFund;
import com.finadv.assets.entities.NSDLReponse;
import com.finadv.assets.entities.NSDLValueTrend;
import com.finadv.assets.entities.OverallStockData;
import com.finadv.assets.entities.PortfolioAnalysisReponse;
import com.finadv.assets.entities.PortfolioAnalysisRequest;
import com.finadv.assets.entities.Transaction;
import com.finadv.assets.entities.UserAsset;
import com.finadv.assets.entities.UserAssets;
import com.finadv.assets.error.RestServiceException;
import com.finadv.assets.util.AssetUtil;

import io.github.jonathanlink.PDFLayoutTextStripper;

@Service
public class CAMSServiceImpl implements CAMSService {

	private AssetService assetService;

	@Autowired
	public void setAssetService(AssetService assetService) {
		this.assetService = assetService;
	}

	@Autowired
	RestTemplate restTemplate;

	@Autowired
	private AssetUtil assetUtil;

	private AsyncService asyncService;

	@Autowired
	public void setAsyncService(AsyncService asyncService) {
		this.asyncService = asyncService;
	}

	private static final Logger LOG = LoggerFactory.getLogger(CAMSServiceImpl.class);

	public static final String MUTUAL_FUND = "Mutual Fund";

	public static final int OPEN_TO_TXN_LINE_SKIP = 1;
	public static final String FOLIO_NO = "FolioNo:";
	public static final String READ_MODE = "r";
	public static final String CLOSING_UNIT_BALANCE = "ClosingUnitBalance:";
	public static final String DATE_TRANSACTION_AMOUNT = "DateTransactionAmount";
	public static final String PAGE_END_REGEX = "Page[0-9]+of[0-9]+";
	public static final int DATE_TRANSACTION_SKIP_LINES = 2;
	public static final String NUMBER_REGEX = "[(),a-z]";
	public static final String PAN = "PAN:";
	public static final String EMAIL_ID = "EmailId";
	public static final String REGULAR = "Regular";
	public static final String DIRECT = "Direct";
	public static final String ADVISOR_REGEX = "Advisor";
	public static final String OPENING_UNIT_BALANCE = "OpeningUnitBalance";
	public static final String AMOUNT_REGEX = "[(),]";

	/**
	 * Extracts MF Details from Mutual Fund CAMS File Generated by user.
	 * 
	 * @param camsFile the multipart cams file.
	 * @param password file password
	 * @throws IOException             exception on parsing pdf.
	 */
	@Override
	public String extractMFData(MultipartFile camsFile, String password, Long userId, String source)
			throws IOException {
		LOG.info("Inside extractMFData for cams userId " + userId);
		String temDirectory = "java.io.tmpdir";
		File tempCAMSFile = new File(System.getProperty(temDirectory) + "/" + camsFile.getOriginalFilename() + "-"
				+ password + RandomStringUtils.random(4, true, true));
		CAMS camsData = new CAMS();
		 PDDocument pdDoc = null;
		 COSDocument cosDoc = null;
		 RandomAccessRead rar = null;
		try {
			camsFile.transferTo(tempCAMSFile);
			// Store file in S3
			asyncService.uploadFile(tempCAMSFile, "cams");

			rar = new RandomAccessFile(tempCAMSFile, READ_MODE);
			PDFParser parser = new PDFParser(rar, password);

			parser.parse();
			cosDoc = parser.getDocument();
			PDFTextStripper pdfStripper = new PDFLayoutTextStripper();
			pdfStripper.setAddMoreFormatting(false);
			pdDoc = new PDDocument(cosDoc);
			pdDoc.setAllSecurityToBeRemoved(true);

			String parsedText = pdfStripper.getText(pdDoc);

			List<String> linesList = parsedText.lines().collect(Collectors.toList());

			boolean summaryFlag = parsedText.contains("Loads  and  Fees") ? true : false;

			HolderInfo holderInfo = new HolderInfo();
			List<FundInfo> fundInfoList = new ArrayList<>();
			for (int folioIndex = 0; folioIndex < linesList.size(); folioIndex++) {
				String line = linesList.get(folioIndex);
				if (line.replaceAll("\\s", "").contains(EMAIL_ID)) {
					holderInfo.setEmail(
							line.substring(0, 70).split(":")[1].strip().trim().replaceAll(" ", "").toLowerCase());
					holderInfo.setName(linesList.get(folioIndex + 2).substring(0, 70).strip());
				}

				if (line.replaceAll("\\s", "").contains(FOLIO_NO) && !summaryFlag) {
					var folio = new FundInfo();
					List<Transaction> transactionList = new ArrayList<>();
					var folioNamePan = line.split(PAN);
					folio.setFolioName(folioNamePan[0].replaceAll("\\s", "").split(":")[1].strip());
					if (folioNamePan.length > 2)
						folio.setPan(folioNamePan[1].strip().substring(0, 10).strip());
					// log.info("Got the Folio No : {}", line);
					String scheme = "";
					for (int txnOpenIndex = folioIndex + 1; txnOpenIndex < linesList.size(); txnOpenIndex++) {
						if (linesList.get(txnOpenIndex).strip().replaceAll("\\s", "").contains(OPENING_UNIT_BALANCE)) {
							scheme = linesList.subList(folioIndex + 1, txnOpenIndex).stream()
									.map(schemeLine -> schemeLine.strip().replaceAll("\\s", ""))
									.collect(Collectors.joining());
							// var schemeAndAdvisor = scheme.split(ADVISOR_REGEX);
							String[] splitScheme = scheme.split("-");
							folio.setSchemeName(scheme);
							if (folio.getSchemeName().contains("KFINTECH")) {
								folio.setRtCode(StringUtils.substring(splitScheme[0], 0, splitScheme[0].length() - 1));
							} else {
								folio.setRtCode(splitScheme[0]);
							}
							folioIndex = txnOpenIndex + OPEN_TO_TXN_LINE_SKIP;
							break;
						}
					}
					// log.info("Got the Scheme : {}", scheme);
					// System.out.println("Got the Scheme : {}" + scheme);
					for (int purchaseListIndex = folioIndex; purchaseListIndex < linesList
							.size(); purchaseListIndex++) {
						if (linesList.get(purchaseListIndex).replaceAll("\\s", "").contains(CLOSING_UNIT_BALANCE)) {
							folio.setClosingBalance(
									parseAmount(linesList.get(purchaseListIndex).substring(0, 50).split(":")[1]));
							folio.setNav(parseAmount(
									linesList.get(purchaseListIndex).substring(50, 100).split(":")[1].split("INR")[1]
											.strip()));
							folio.setValuation(parseAmount(
									linesList.get(purchaseListIndex).substring(100).split(":")[1].split("INR")[1]
											.strip()));
							Transaction lastTransaction = new Transaction();
							lastTransaction.setDate(extractTransactionDate(linesList.get(purchaseListIndex - 1)));
							for (int transactionIndex = folioIndex; transactionIndex < purchaseListIndex; transactionIndex++) {
								String transactionDetail = linesList.get(transactionIndex).strip();
								if (transactionDetail.replaceAll("\\s", "").matches(PAGE_END_REGEX)) {
									// log.info(transactionDetail);
									// log.info("Looks like we have hit a page ending, searching for transactions in
									// next page...");
									for (int pageEndIndex = transactionIndex; pageEndIndex < linesList
											.size(); pageEndIndex++) {
										if (linesList.get(pageEndIndex).strip().replaceAll("\\s", "")
												.contains(DATE_TRANSACTION_AMOUNT)) {
											// log.info("Got the continued transaction list!");
											transactionIndex = pageEndIndex + DATE_TRANSACTION_SKIP_LINES;
											break;
										}
									}
								} else {
									if (transactionDetail.length() != 0) {
										Transaction t = getTransactionDetails(transactionDetail);
										if (t.getDate() != null)
											transactionList.add(t);
									}
									// log.info(transactionDetail);
								}
							}
							// log.info("Transactions extracted for scheme : " + scheme);
							folio.setTransactions(transactionList);
							folioIndex = purchaseListIndex;
							break;
						}
					}
					fundInfoList.add(folio);
				}
			}

			if (summaryFlag) {
				int indexOpt = IntStream.range(0, linesList.size()).filter(i -> linesList.get(i).contains("Folio  No."))
						.findFirst().orElse(-1);
				;
				for (int i = indexOpt + 2; i < linesList.size(); i++) {
					FundInfo folio = new FundInfo();
					if (linesList.get(i).trim().contains("Total"))
						break;
					if (linesList.get(i).trim().matches("^[0-9].*$")) {
						String[] splitLine = linesList.get(i).trim().split("\\s+");
						folio.setFolioName(splitLine[0]);
						if (splitLine[splitLine.length - 1].contains("KFINTECH")) {

							String rtCode = (Stream.of(splitLine[1].split("-")).reduce((first, last) -> first).get());
							folio.setRtCode(StringUtils.substring(rtCode, 0, rtCode.length() - 1));
						} else {
							folio.setRtCode((Stream.of(splitLine[1].split("-")).reduce((first, last) -> first).get()));
						}
						folio.setValuation(Double.valueOf(splitLine[splitLine.length - 2].replaceAll(",", "").trim()));
						folio.setClosingBalance(
								Double.valueOf(splitLine[splitLine.length - 5].replaceAll("[A-Za-z,()-]", "").trim()));
						folio.setNav(Double.valueOf(splitLine[splitLine.length - 3].replaceAll(",", "").trim()));

						StringBuffer name = new StringBuffer();
						for (int j = 1; j < splitLine.length - 5; j++) {
							if (splitLine[j].contains("-"))
								break;
							name.append(splitLine[j]).append(" ");
						}
						folio.setSchemeName(name.toString());

						fundInfoList.add(folio);
					}

				}
			}

			camsData.setFundInfoList(fundInfoList);
			camsData.setHolderInfo(holderInfo);
			List<UserAssets> userAssetList = new ArrayList<UserAssets>();
			for (FundInfo fundInfo : camsData.getFundInfoList()) {
				if (fundInfo.getValuation() != 0) {
					UserAssets userAssets = new UserAssets();
					userAssets.setAmount(fundInfo.getValuation());
					userAssets.setHolderName(camsData.getHolderInfo().getName());
					userAssets.setNickName(camsData.getHolderInfo().getEmail());
					userAssets.setCreatedAt(LocalDateTime.now());
					Institution institution = new Institution();
					institution.setId(1);
					userAssets.setAssetProvider(institution);
					AssetType assetType = new AssetType();
					assetType.setId(4);
					assetType.setTypeName("equity");
					userAssets.setAssetType(assetType);
					AssetInstrument assetInstrument = new AssetInstrument();
					assetInstrument.setId(8);
					userAssets.setAssetInstrument(assetInstrument);
					userAssets.setExpectedReturn(12);
					userAssets.setEquityDebtName(fundInfo.getSchemeName());
					userAssets.setCode(fundInfo.getRtCode());
					userAssets.setUnits((int) Math.round(fundInfo.getValuation() / fundInfo.getNav()));

					userAssets.setUserId(userId);
					userAssetList.add(userAssets);
				}

			}

			UserAsset userAsset = new UserAsset();
			userAsset.setUserId(userId);
			userAsset.setAssets(userAssetList);
			// temp comment
			if ("portal".equalsIgnoreCase(source)) {
				LOG.info("extractMFData Not saving assets from cams " + camsFile.getOriginalFilename());
				assetService.saveUserAssetsByUserId(userAsset, "cams");
			}

			
			rar.close();
			cosDoc.close();
			pdDoc.close();
			//Not deleting as temporarily storing file in AWS S3
			//tempCAMSFile.delete();
			LOG.info("Exit extractMFData for cams userId " + userId);

			return new ObjectMapper().writeValueAsString(camsData);

		} catch (IllegalStateException | IOException e) {
			throw new RestServiceException(HttpStatus.BAD_REQUEST, e);
		}finally {
			if (rar != null)
			rar.close();
			if (cosDoc != null)
			cosDoc.close();
			if (pdDoc != null)
			pdDoc.close();
			// Delete the file
			FileUtils.deleteQuietly(tempCAMSFile);
			//tempCAMSFile.delete();
		}

	}

	private LocalDate extractTransactionDate(String transactionLine) {
		try {
			return LocalDate.parse(transactionLine.strip().substring(0, 11),
					DateTimeFormatter.ofPattern("dd-MMM-yyyy"));
		} catch (Exception e) {
			// log.error("Ignored error : {}", e.getMessage());
		}
		return null;
	}

	private Transaction getTransactionDetails(String transactionDetail) {
		Transaction transaction = new Transaction();
		try {
			if (transactionDetail.contains("***")) {
				return transaction;
			}

			var date = transactionDetail.substring(0, 11);
			transaction.setDate(LocalDate.parse(date, DateTimeFormatter.ofPattern("dd-MMM-yyyy")));
			if (transactionDetail.contains("(")) {
				// System.out.println(transactionDetail);
			} else {

				String[] lineSplitter = Arrays.asList(transactionDetail.split(" ")).stream()
						.filter(str -> !str.isEmpty()).collect(Collectors.toList()).toArray(new String[0]);

				transaction.setTransactionDetail(lineSplitter[1].trim());
				transaction.setAmount(parseAmount(lineSplitter[lineSplitter.length - 4].trim()));
				transaction.setUnits(
						Double.valueOf(lineSplitter[lineSplitter.length - 3].trim().replaceAll(AMOUNT_REGEX, "")));
				transaction.setPrice(
						Double.valueOf(lineSplitter[lineSplitter.length - 2].trim().replaceAll(AMOUNT_REGEX, "")));
				transaction.setUnitBalance(
						Double.valueOf(lineSplitter[lineSplitter.length - 1].trim().replaceAll(AMOUNT_REGEX, "")));
				// System.out.println(transactionDetail.substring(12, 79));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

		return transaction;
	}

	private static Double parseAmount(String amountString) {
		return Double.valueOf(amountString.strip().replaceAll(AMOUNT_REGEX, ""));
	}

	@Override
	public NSDLReponse portfolioAnalyzeCAMS(MultipartFile camsFile, String password, Long userId, String source)
			throws IOException {
		LOG.info("Inside portfolioAnalyzeCAMS for cams file " + camsFile.getOriginalFilename());
		NSDLReponse nsdlReponse = new NSDLReponse();
		String data = extractMFData(camsFile, password, userId, source);
		ObjectMapper objectMapper = new ObjectMapper();
		objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
		CAMS camsData = objectMapper.readValue(data, CAMS.class);

		// Analyse Mutual fund portfolio for the user
		nsdlReponse.setHolderName(camsData.getHolderInfo().getName());

		// SET TOTAL AMOUNT
		double mfTotalAmount = camsData.getFundInfoList().stream().mapToDouble(FundInfo::getValuation).sum();
		nsdlReponse.setAmount(mfTotalAmount);

		nsdlReponse.setNsdlEquities(new ArrayList<NSDLEquity>());
		// Mutual fund setters
		List<NSDLMutualFund> nsdlMfList = camsData.getFundInfoList().stream()
				.map(mf -> new NSDLMutualFund(mf.getRtCode(), mf.getSchemeName(), mf.getClosingBalance().floatValue(),
						mf.getValuation()))
				.collect(Collectors.toList());
		nsdlReponse.setNsdlMutualFunds(nsdlMfList);

		List<NSDLValueTrend> valuetrend = new ArrayList<NSDLValueTrend>();
		nsdlReponse.setNsdlValueTrend(valuetrend);
		NSDLAssetAmount nsdlAssetAmount = new NSDLAssetAmount();
		nsdlAssetAmount.setMutualFundFolios(Double.valueOf(mfTotalAmount).longValue());
		nsdlReponse.setNsdlAssetAmount(nsdlAssetAmount);
		
		if (nsdlReponse.getNsdlMutualFunds().size() > 0)
			getAnalysisData(nsdlReponse, camsData.getHolderInfo().getEmail(), camsFile.getOriginalFilename(), password);

		return nsdlReponse;
	}

	private void getAnalysisData(NSDLReponse nsdlReponse, String email, String fileName, String password) {
		LOG.info("Inside getAnalysisData for cams file " + fileName);
		// map rtcode from cams with their corresponding isin
		String equityMFRtCodeList = nsdlReponse.getNsdlMutualFunds().stream().map(NSDLMutualFund::getIsin)
				.collect(Collectors.joining(","));
		FundDataList fundDataList = getSchemeDetails(equityMFRtCodeList);

		for (NSDLMutualFund mf : nsdlReponse.getNsdlMutualFunds()) {
			FundDataResponse fdResponse = fundDataList.getResponse().stream()
					.filter(x -> x.getData() != null && StringUtils.isNotEmpty(x.getData().getRtcode())
							&& x.getData().getRtcode().equalsIgnoreCase(mf.getIsin()))
					.findFirst().orElse(null);
			if (fdResponse != null && StringUtils.isNoneEmpty(fdResponse.getData().getIsin())) 
				mf.setIsin(fdResponse.getData().getIsin());
			if (fdResponse != null && StringUtils.isNoneEmpty(fdResponse.getData().getSchemenamecmapis()))
				mf.setIsinDescription(fdResponse.getData().getSchemenamecmapis());

		}

		// Get mutual fund underlying stocks
		MutualFundAnalysisResponseList mutualFundAnalysisResponseList = getSchemeAnalysis(
				nsdlReponse.getNsdlMutualFunds());
		mutualFundAnalysisResponseList.getMfaResponse()
				.sort(Comparator.comparing(MutualFundAnalysisResponse::getAmount).reversed());
		nsdlReponse.setMfaResponse(mutualFundAnalysisResponseList.getMfaResponse());
		nsdlReponse.setMfAnalyzed(mutualFundAnalysisResponseList.getMfAnalyzed());
		nsdlReponse.setMfNotAnalyzed(mutualFundAnalysisResponseList.getMfNotAnalyzed());
		nsdlReponse.setMfGrowthAnalysis(mutualFundAnalysisResponseList.getMfGrowthAnalysis());

		List<OverallStockData> overallStock = mutualFundAnalysisResponseList.getMfaResponse().stream()
				.map(m -> new OverallStockData(m.getSymbol(), m.getAmount(),
						(float) ((m.getAmount()
								/ (nsdlReponse.getAmount() - mutualFundAnalysisResponseList.getAmountNotAnalyzed()))
								* 100),
						(long) m.getAmount(), 0, m.getIndustry()))
				.collect(Collectors.toList());

		overallStock.sort(Comparator.comparing(OverallStockData::getCurrentValue).reversed());

		nsdlReponse.setOverallStock(overallStock);

		// Calculate mf sector details
		if (nsdlReponse.getNsdlMutualFunds().size() > 0) {

			Map<String, Double> mfMap = mutualFundAnalysisResponseList.getMfaResponse().stream()
					.collect(Collectors.groupingBy(mf -> mf.getIndustry().toUpperCase(),
							Collectors.summingDouble(MutualFundAnalysisResponse::getAmount)));

			Map<String, Double> mfMapSorted = mfMap.entrySet().stream()
					.sorted(Map.Entry.comparingByValue(Comparator.reverseOrder()))
					.collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue, (oldValue, newValue) -> oldValue,
							LinkedHashMap::new));

			nsdlReponse.setMfSector(mfMapSorted);
		}

		// Calculate overall sector details
		if (nsdlReponse.getOverallStock().size() > 0) {

			Map<String, Double> oMap = nsdlReponse.getOverallStock().stream().collect(Collectors.groupingBy(
					os -> os.getSector().toUpperCase(), Collectors.summingDouble(OverallStockData::getCurrentValue)));
			Map<String, Double> oMapSorted = oMap.entrySet().stream()
					.sorted(Map.Entry.comparingByValue(Comparator.reverseOrder()))
					.collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue, (oldValue, newValue) -> oldValue,
							LinkedHashMap::new));
			nsdlReponse.setOverallSector(oMapSorted);
		}

		// Get portfolio analysis
		PortfolioAnalysisReponse portfolioAnalysisReponse = getPortfolioAnalysis(nsdlReponse.getNsdlMutualFunds(),
				nsdlReponse.getNsdlEquities());
		nsdlReponse.setPortfolioAnalysis(portfolioAnalysisReponse);

		// Save user data for future
		asyncService.saveNSDLData(nsdlReponse.getHolderName(), email, fileName, password);
	}

	private MutualFundAnalysisResponseList getSchemeAnalysis(List<NSDLMutualFund> nsdlMutualFunds) {
		if (!nsdlMutualFunds.isEmpty()) {
			LOG.info("API call to POST mutual fund underlying stocks : " + nsdlMutualFunds.size());

			StringBuilder getMFAnalysisURL = new StringBuilder(assetUtil.getProperty("mf.base.url"));
			getMFAnalysisURL.append(assetUtil.getProperty("mf.analysis.url.path"));

			HttpHeaders headers = new HttpHeaders();
			headers.set("Accept", MediaType.APPLICATION_JSON_VALUE);

			UriComponentsBuilder builder = UriComponentsBuilder.fromHttpUrl(getMFAnalysisURL.toString())
					.queryParam("source", "nsdl");
			MutualFundAnalysis mutualFundAnalysis = new MutualFundAnalysis();
			List<MutualFundAnalysisScheme> mfSchemes = nsdlMutualFunds.stream()
					.map(n -> new MutualFundAnalysisScheme(
							Stream.of(n.getIsinDescription().trim().split("-")).reduce((first, last) -> first).get(),
							n.getCurrentValue(), n.getIsin().trim()))
					.collect(Collectors.toList());
			mutualFundAnalysis.setMfSchemes(mfSchemes);
			HttpEntity<?> entity = new HttpEntity<>(mutualFundAnalysis, headers);

			ResponseEntity<MutualFundAnalysisResponseList> response = restTemplate
					.postForEntity(builder.build().toUri(), entity, MutualFundAnalysisResponseList.class);

			LOG.info("API Response for  POST mutual fund underlying stocks : " + response.getStatusCodeValue());
			return response.getBody();

		}
		return new MutualFundAnalysisResponseList();
	}

	private PortfolioAnalysisReponse getPortfolioAnalysis(List<NSDLMutualFund> nsdlMutualFunds,
			List<NSDLEquity> nsdlEquities) {
		LOG.info("API call to POST Portfolio analysis FOR EQUITIES " + nsdlEquities.size() + " and for schemes : "
				+ nsdlMutualFunds.size());

		PortfolioAnalysisRequest portfolioAnalysisRequest = new PortfolioAnalysisRequest();

		StringBuilder postPorfolioAnalysisURL = new StringBuilder(assetUtil.getProperty("portfolio.base.url"));
		postPorfolioAnalysisURL.append(assetUtil.getProperty("portfolio.analysis.url.path"));

		HttpHeaders headers = new HttpHeaders();
		headers.set("Accept", MediaType.APPLICATION_JSON_VALUE);

		UriComponentsBuilder builder = UriComponentsBuilder.fromHttpUrl(postPorfolioAnalysisURL.toString())
				.queryParam("source", "nsdl");
		MutualFundAnalysis mutualFundAnalysis = new MutualFundAnalysis();
		List<MutualFundAnalysisScheme> mfSchemes = nsdlMutualFunds.stream()
				.map(n -> new MutualFundAnalysisScheme(
						Stream.of(n.getIsinDescription().trim().split("-")).reduce((first, last) -> first).get(),
						n.getCurrentValue(), n.getIsin().trim()))
				.collect(Collectors.toList());

		portfolioAnalysisRequest.setMfSchemes(mfSchemes);

		List<Equity> equities = new ArrayList<Equity>();
		if (nsdlEquities.size() > 0)
			equities = nsdlEquities.stream().map(n -> new Equity(n.getIsin(), n.getCurrentValue()))
					.collect(Collectors.toList());

		portfolioAnalysisRequest.setEquities(equities);

		HttpEntity<?> entity = new HttpEntity<>(portfolioAnalysisRequest, headers);

		ResponseEntity<PortfolioAnalysisReponse> response = restTemplate.postForEntity(builder.build().toUri(), entity,
				PortfolioAnalysisReponse.class);
		LOG.info("API call to POST Portfolio analysis " + response.getStatusCodeValue());
		return response.getBody();

	}

	private FundDataList getSchemeDetails(String equityMFRtCodeList) {
		if (StringUtils.isNoneEmpty(equityMFRtCodeList)) {
			LOG.info("API call to GET details for mutual funds : " + equityMFRtCodeList);
			StringBuilder getSchemeURL = new StringBuilder(assetUtil.getProperty("fund.base.url"));
			getSchemeURL.append(assetUtil.getProperty("fund.schemes.url.path"));

			HttpHeaders headers = new HttpHeaders();
			headers.set("Accept", MediaType.APPLICATION_JSON_VALUE);

			UriComponentsBuilder builder = UriComponentsBuilder.fromHttpUrl(getSchemeURL.toString())
					.queryParam("rtcode", equityMFRtCodeList);

			HttpEntity<?> entity = new HttpEntity<>(headers);

			ResponseEntity<FundDataList> response = restTemplate.exchange(builder.toUriString(), HttpMethod.GET, entity,
					FundDataList.class);
			LOG.info("API Response for GET mutual fund call " + response.getStatusCodeValue());
			return response.getBody();

		}
		return new FundDataList();
	}
}
